### ISSUE TITLE
cripples ppx_deriving

### ISSUE THREAD

**Issue by choeger** [janestreet/ppx_type_conv#12]
ppx_deriving has a useful shorthand syntax for inline-derivations. This functionality is removed by ppx_type_conv.

```
#use "topfind" ;;
#require "ppx_deriving.show";;
let foo = [%derive.show : string] ;;

#require "ppx_sexp_conv";;
let bar = [%derive.show : string] ;;
```

The second derivation remains untranslated, because of the dark magic that ppx_type_conv invokes.

**Comment by ghost** [comment]
Do you still have this problem? If yes, can you provide the versions of the compiler and packages you are using.

**Comment by ghost** [comment]
I tested the example given with https://github.com/ocaml/opam-repository/pull/10885 and the issue was gone
